---
- name: rhel | install | installing pre-reqs
  apt: name={{ item }} state=present
  with_items:
    - python-software-properties
    - xfsprogs

- name: rhel | install | installing glusterfs server
  yum:
    name: glusterfs-server 
    state: latest
  when: glusterfs_server

- name: rhel | install | installing glusterfs client
  yum: 
    name: glusterfs-client 
    state: latest
  when: glusterfs_client

- name: rhel | config | enabling glusterfs-server
  service: 
     name: glusterfs-server 
     enable: yes
  when: glusterfs_server
